<a href="https://colab.research.google.com/github/pamelallc/LJAWeek4Warmup/blob/main/Copy_of_Week_1_Homework_(Pamela_Low).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1 Homework

(Be sure to save this to Drive before starting)

For this week we are going to practice requesting information from an API and manipulating it as JSON and as a Dataframe.

We are going to keep working with Collection Builder. Head over to the [Collection Builder Example Projects](https://collectionbuilder.github.io/cb-examples/browse.html) listing and find a site that interests you. Spend some time browsing the website to get acquainted with its contents before proceeding with the questions.

In [1]:
#The Libraries we will need
import requests
import json
import pandas as pd
from random import randrange

In [2]:
# @markdown **H1** Find the URL of for the  _metadata.json_ of your selected site and paste it in here.
json_cb_url = "https://uwtacomalibrary.github.io/TJLS/assets/data/metadata.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_url)
#all of the data from the sites
total_cb_data = response_cb.json()
#just the 'objects' indexed in the site
objects_cb_data = total_cb_data['objects']
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

**H2** Run the 'show random cell' a few times to get a sense of what kind of data is in your chosen site.

In [3]:
#Run this a few times to see random entries in the JSON data that you retrieved.
random_entry = randrange(len(objects_cb_data))
print(json.dumps(objects_cb_data[random_entry],indent=2))

{
  "title": "Large group of students and adults in front of the Tacoma Japanese Language School gathered to celebrate the visit of Duke Tokugawa, March 4, 1934",
  "creator": "Boland, M. D. (Marvin Dement)",
  "date": "1934",
  "description": "Written on photo in Japanese: SHoWA 9-NEN 3-GATSU 4-KA TOGUGAWA KoSHAKU KAKKA GOSHI KINEN SATUEI Translation: Commemorating the visit of his excellency Duke Tokugawa to Tacoma, WA on March 4, 1934. Handwritten on verso in Japanese: Fujimoto.",
  "subject": "Japanese students--Washington (State)--Tacoma; School buildings--Washington (State)--Tacoma; Nihongo Gakko (Tacoma, Wash.)--Students; Portraits, Group--Washington (State)--Tacoma",
  "location": "Tacoma, Washington, United States",
  "source": "Photographs of the Tacoma Japanese Language School and Tacoma Hongwanji Buddhist Church. PH Coll 1021",
  "type": "image",
  "format": "image/jpeg",
  "language": "eng",
  "object_thumb": "https://digitalcollections.lib.washington.edu/digital/api/singleitem/image/panoram/117/default.jpg?highlightTerms=PH%20Coll%201020",
  "object_location": "https://digitalcollections.lib.washington.edu/digital/iiif/panoram/117/full/full/0/default.jpg",
  "reference_url": "erika-b.github.io/TJLS/items/largegroup1934.html"
}

## Different Fields!

You can create any number of datafields and correpsonding values for those fields with a Collection Builder site. So the results from the output from the cell above will probably have wildly different results from [my site](https://elibtronic.github.io/AIL_Database/data.html) that we worked on in the Workalong notebook.


You can see all of these options from grabbing the _facets.json_ URL from a collection builder homepage. Find that URL for your selected site for **H3**

In [4]:
# @markdown **H3** Find the URL of the facets.json for your selected site and paste it in here.
json_cb_facets_url = "https://uwtacomalibrary.github.io/TJLS/assets/data/facets.json" # @param {"type":"string","placeholder":""}

response_cb = requests.get(json_cb_facets_url)
#all of the data from the sites
total_facet_data = response_cb.json()
#just the 'objects' indexed in the site
print("Data fetched and JSON constructed!")

Data fetched and JSON constructed!

Run the cell below to see what the facets used for this site:

In [5]:
print(json.dumps(total_facet_data,indent=2))
#Why are other headings like Creator and Date not displayed? Are they not facets too?

{
  "facets": [
    {
      "field": "subject",
      "terms": {
        "japanese students--washington (state)--tacoma": 3,
        "school buildings--washington (state)--tacoma": 3,
        "nihongo gakko (tacoma, wash.)--students": 3,
        "portraits, group--washington (state)--tacoma": 2,
        "nihongo gakko (tacoma, wash.)--faculty": 2,
        "military officers--washington (state)--tacoma": 1
      }
    },
    {
      "field": "creator",
      "terms": {
        "boland, m. d. (marvin dement)": 3,
        "hata, jack kazuo": 1,
        "hattori, fumi (sato)": 1,
        "horita, kazuo": 1,
        "hayashi, june mieko (shirozu)": 1,
        "takaoka, chizu": 1,
        "takasugi, mitsuo": 1,
        "taniguichi, taeko (hoshiwara)": 1,
        "torimaru, hanna kae (nakagawa)": 1,
        "yano, perry yoshiaki": 1,
        "yoshioka, betty hiroko (fukuhara)": 1,
        "chapin bowen inc.": 1,
        "cysewski, stephen": 1,
        "hoffman, lisa": 1,
        "hanneman, mary": 1
      }
    },
    {
      "field": "format",
      "terms": {
        "image/jpeg": 16,
        "compound_object": 10,
        "csv": 1,
        "audio/mp3": 1,
        "video/mp4": 1
      }
    }
  ]
}

**H3** Try to read the JSON that is displayed to the screen. What possible facets are there in the the data. Fill them in the markdown list in the cell below. Add as many entries as you need to describe the site

Facets in my site are:
- Subject
- Creator
- Format

**H4** Which facet shows up the most for your selected site? Put your answer in the cell below

This facet that shows up the most is Format it is used 29 times on my selected site.

**H5** Turn the site _metadata.json_ data into a dataframe by completing the cell below. Part of it is written for you. You just need to modify line 4.

In [6]:
#H5

cb_data = pd.read_json(json_cb_url)
cb_normalized = pd.json_normalize(cb_data['objects'])
cb_normalized

,title,creator,date,description,location,people,organizations,places,source,type,format,language,rights,rightsstatement,object_thumb,object_location,reference_url,subject
0,Jack Kazuo Hata Oral History,"Hata, Jack Kazuo",2005-01-30,Jack Kazuo Hata recounts his childhood growing...,"Los Angeles, California, United States; Toyama...","Myer, Dillon; Heatter, Gabriel; Hata, Jack Kaz...",Longfellow Elementary School; Morton M. McCarv...,Fawcett Avenue; Winthrop Hotel; Robert M. Smit...,Tacoma Japanese Language School Project,record,compound_object,eng,This item is protected by copyright and/or rel...,http://rightsstatements.org/vocab/InC-EDU/1.0/,erika-b.github.io/TJLS/objects/thumbs/jhata_im...,https://youtu.be/L1TiCeZoLTk,erika-b.github.io/TJLS/items/jhata.html,NaN
1,Jack Kazuo Hata image,NaN,2005-01-30,NaN,NaN,NaN,NaN,NaN,NaN,image;stillimage,image/jpeg,eng,NaN,NaN,erika-b.github.io/TJLS/objects/thumbs/jhata_im...,erika-b.github.io/TJLS/objects/jhata_image.jpg,erika-b.github.io/TJLS/items/jhata2.html,NaN
2,Fumi (Sato) Hattori Oral History,"Hattori, Fumi (Sato)",2005-01-27,Fumi (Sato) Hattori looks back on her childhoo...,"Tacoma, Washington, United States; Ehime Prefe...","Sato, Hidamaru; Sato, Masahiro; Sato, Toshiats...",St. Paul Tacoma Lumber Company; Stadium High S...,St. Paul Avenue; Superior Hotel,Tacoma Japanese Language School Project,record,compound_object,eng,This item is protected by copyright and/or rel...,http://rightsstatements.org/vocab/InC-EDU/1.0/,erika-b.github.io/TJLS/objects/thumbs/shattori...,https://youtu.be/LdopnmPw9t4,erika-b.github.io/TJLS/items/shattori.html,NaN
3,Fumi (Sato) Hattori image,NaN,2005-01-27,NaN,NaN,NaN,NaN,NaN,NaN,image;stillimage,image/jpeg,eng,NaN,NaN,erika-b.github.io/TJLS/objects/thumbs/shattori...,erika-b.github.io/TJLS/objects/shattori_image.jpg,erika-b.github.io/TJLS/items/shattori3.html,NaN
4,Kazuo Horita Oral History,"Horita, Kazuo",2005-03-11,Kazuo Horita shares his unique family history ...,"Fukui Prefecture, Japan; Chicago, Illinois, Un...","Ichio, Akiyo; Ikeda, Taki; Horita, Tom; Godfri...",Tacoma Buddhist Temple; Whitney Memorial Unite...,1124 Market Street,Tacoma Japanese Language School Project,record,compound_object,eng,This item is protected by copyright and/or rel...,http://rightsstatements.org/vocab/InC-EDU/1.0/,erika-b.github.io/TJLS/objects/thumbs/khorita_...,,erika-b.github.io/TJLS/items/khorita.html,NaN
5,Kazuo Horita transcript,NaN,2005-03-11,NaN,NaN,NaN,NaN,NaN,NaN,text,csv,eng,NaN,NaN,NaN,erika-b.github.io/TJLS/objects/khorita.csv,erika-b.github.io/TJLS/items/khorita1.html,NaN
6,Kazuo Horita audio,NaN,2005-03-11,NaN,NaN,NaN,NaN,NaN,NaN,sound,audio/mp3,eng,NaN,NaN,NaN,erika-b.github.io/TJLS/objects/khorita_audio_w...,erika-b.github.io/TJLS/items/khorita2.html,NaN
7,Kazuo Horita image,NaN,2005-03-11,NaN,NaN,NaN,NaN,NaN,NaN,image;stillimage,image/jpeg,eng,NaN,NaN,NaN,erika-b.github.io/TJLS/objects/khorita_image.jpg,erika-b.github.io/TJLS/items/khorita3.html,NaN
8,June Mieko (Shirozu) Hayashi Oral History,"Hayashi, June Mieko (Shirozu)",2005-01-27,June Mieko (Shirozu) Hayashi traces her family...,"Altadena, California, United States; Longview,...","Isau, Mason (Shirozu); Reiko, Dorothy (Shirozu...",Central School; Japanese American National Mus...,Fawcett Avenue; Whitney Memorial United Method...,Tacoma Japanese Language School Project,record,compound_object,eng,This item is protected by copyright and/or rel...,http://rightsstatements.org/vocab/InC-EDU/1.0/,erika-b.github.io/TJLS/objects/thumbs/jhayashi...,https://youtu.be/N26x0Glv_us,erika-b.github.io/TJLS/items/jhayashi.html,NaN
9,June Mieko (Shirozu) Hayashi image,NaN,2005-01-29,NaN,NaN,NaN,NaN,NaN,NaN,image;stillimage,image/jpeg,eng,NaN,NaN,erika-b.github.io/TJLS/objects/thumbs/jhayashi...,erika-b.github.io/TJLS/objects/jhayashi_image.jpg,erika-b.github.io/TJLS/items/jhayashi3.html,NaN
10,Chizu Takaoka Oral History,"Takaoka, Chizu",2005-03-12,Chizu Takaoka traces her family history from J...,"Tacoma, Washington, United States; Fukushima, ...","Tomita, Tainojo; Nihei, Kin; Suzuki, Daise; Ho...",Central School; Morton M. McCarver Middle Scho...,Wright Park; Pearl Harbor; Tule Lake War Reloc...,Tacoma Japanese Language School Project,record,compound_object,eng,This item is protected by copyright and/or rel...,http://rightsstatements.org/page/InC-EDU/1.0/?...,erika-b.github.io/TJLS/objects/thumbs/ctakaoka...,https://youtu.be/s6N63V7uSK4,erika-b.github.io/TJLS/items/ctakaoka.html,NaN
11,Chizu Takaoka image,NaN,2005-03-12,NaN,NaN,NaN,NaN,NaN,NaN,image;stillimage,image/jpeg,eng,NaN,NaN,erika-b.github.io/TJLS/objects/thumbs/ctakaoka...,erika-b.github.io/TJLS/objects/ctakaoka_image.jpg,erika-b.github.io/TJLS/items/ctakaoka3.html,NaN
12,Mitsuo Takasugi Oral History,"Takasugi, Mitsuo",2005-01-09,Mitsuo Takasugi reflects on his childhood grow...,"Los Angeles, California, United States; Tacoma...","Emperor Meiji (Meiji the Great); Yamasaki, Mas...",Central School; Morton M. McCarver Middle Scho...,Sheraton Hotel Tacoma (Hotel Murano); Washingt...,Tacoma Japanese Language School Project,record,compound_object,eng,This item is protected by copyright and/or rel...,http://rightsstatements.org/vocab/InC-EDU/1.0/,erika-b.github.io/TJLS/objects/thumbs/mtakasug...,https://youtu.be/Z0GmiEp4BtU,erika-b.github.io/TJLS/items/mtakasugi.html,NaN
13,Mitsuo Takasugi image,NaN,2005-01-09,NaN,NaN,NaN,NaN,NaN,NaN,image;stillimage,image/jpeg,eng,NaN,NaN,erika-b.github.io/TJLS/objects/thumbs/mtakasug...,erika-b.github.io/TJLS/objects/mtakasugi_image...,erika-b.github.io/TJLS/items/mtakasugi3.html,NaN
14,Taeko (Hoshiwara) Taniguichi Oral History,"Taniguichi, Taeko (Hoshiwara)",2006-03-17,Taeko Taniguishi Hoshiwara describes growing u...,"Seattle, Washington, United States; Honolulu, ...","Tanbara, Kimi; Taniguichi, Taeko (Hoshiwara); ...",United States. War Relocation Authority; Rose ...,Traveler's Hotel; Pearl Harbor; Publix Hotel; ...,Tacoma Japanese Language School Project,record,compound_object,eng,This item is protected by copyright and/or rel...,http://rightsstatements.org/vocab/InC-EDU/1.0/,erika-b.github.io/TJLS/objects/thumbs/ttanigui...,https://youtu.be/DJw4DUWVU-0,erika-b.github.io/TJLS/items/ttaniguichi.html,NaN
15,Taeko (Hoshiwara) Taniguichi image,NaN,2006-03-17,NaN,NaN,NaN,NaN,NaN,NaN,image;stillimage,image/jpeg,eng,NaN,NaN,erika-b.github.io/TJLS/objects/thumbs/ttanigui...,erika-b.github.io/TJLS/objects/ttaniguichi_ima...,erika-b.github.io/TJLS/items/ttaniguichi3.html,NaN
16,Hanna Kae (Nakagawa) Torimaru Oral History,"Torimaru, Hanna Kae (Nakagawa)",2005-03-12,Hanna Kae Nakagawa Torimaru recounts her famil...,"Chicago, Illinois, United States; Tulelake, Ca...","Pei, I. M.; Torimaru, Hanna Kae (Nakagawa)",Tacoma Secretarial School; Central School; Lon...,Tacoma City Hall; State Cafe (Furusato); Carlt...,Tacoma Japanese Language School Project,record,compound_object,eng,This item is protected by copyright and/or rel...,http://rightsstatements.org/vocab/InC-EDU/1.0/,erika-b.github.io/TJLS/objects/thumbs/htorimar...,https://youtu.be/QBPnCDrNMW8,erika-b.github.io/TJLS/items/htorimaru.html,NaN
17,Hanna Kae (Nakagawa) Torimaru image,NaN,2005-03-12,NaN,NaN,NaN,NaN,NaN,NaN,image;stillimage,image/jpeg,eng,NaN,NaN,erika-b.github.io/TJLS/objects/thumbs/htorimar...,erika-b.github.io/TJLS/objects/htorimaru_image...,erika-b.github.io/TJLS/items/htorimaru3.html,NaN
18,Perry Yoshiaki Yano Oral History,"Yano, Perry Yoshiaki",2005-03-10,Perry Yoshiaki Yano recounts his childhood in ...,"Naperville, Illinois, United States; Tacoma, W...","Hashimoto, Henry; Yamasaki, Masato; Yamasaki, ...",Tacoma General Hospital; Central School; Stanl...,Yao's Grocery; Fort Steilacoom; Point Defiance...,Tacoma Japanese Language School Project,record,compound_object,eng,This item is protected by copyright and/or rel...,http://rightsstatements.org/vocab/InC-EDU/1.0/,erika-b.github.io/TJLS/objects/thumbs/pyoshiak...,https://youtu.be/qxDeh80UvT8,erika-b.github.io/TJLS/items/pyoshiaki.html,NaN
19,Perry Yoshiaki Yano image,NaN,2005-03-10,NaN,NaN,NaN,NaN,NaN,NaN,image;stillimage,image/jpeg,eng,NaN,NaN,erika-b.github.io/TJLS/objects/thumbs/pyoshiak...,erika-b.github.io/TJLS/objects/pyoshiaki_image...,erika-b.github.io/TJLS/items/pyoshiaki3.html,NaN
20,Betty Hiroko (Fukuhara) Yoshioka Oral History,"Yoshioka, Betty Hiroko (Fukuhara)",2005-03-10,"Hiroko ""Betty"" Fukuhara Yoshioka describes her...","Tacoma, Washington, United States; Chicago, Il...","Yoshioka, Akiko (Iris); Yoshioka, Sada (Sally)...",Central School; Morton M. McCarver Middle Scho...,Fawcett Avenue; Pearl Harbor,Tacoma Japanese Language School Project,record,compound_object,eng,This item is protected by copyright and/or rel...,http://rightsstatements.org/vocab/InC-EDU/1.0/,erika-b.github.io/TJLS/objects/thumbs/hyoshiok...,https://youtu.be/25-tdb1QQNw,erika-b.github.io/TJLS/items/hyoshioka.html,NaN
21,Betty Hiroko (Fukuhara) Yoshioka image,NaN,2005-03-10,NaN,NaN,NaN,NaN,NaN,NaN,image;stillimage,image/jpeg,eng,NaN,NaN,erika-b.github.io/TJLS/objects/thumbs/hyoshiok...,erika-b.github.io/TJLS/objects/hyoshioka_image...,erika-b.github.io/TJLS/items/hyoshioka3.html,NaN
22,Group of students and faculty outside the rear...,"Boland, M. D. (Marvin Dement)",1927-05-22,Written on photo: Tacoma Kokugo Gakko Kenchiku...,"Tacoma, Washington, United States",NaN,NaN,NaN,Photographs of the Tacoma Japanese Language Sc...,image,image/jpeg,eng,NaN,NaN,https://digitalcollections.lib.washington.edu/...,https://digitalcollections.lib.washington.edu/...,erika-b.github.io/TJLS/items/largegroup1927.html,NaN
23,Large group of students and adults in front of...,"Boland, M. D. (Marvin Dement)",1934,Written on photo in Japanese: SHoWA 9-NEN 3-GA...,"Tacoma, Washington, United States",NaN,NaN,NaN,Photographs of the Tacoma Japanese Language Sc...,image,image/jpeg,eng,NaN,NaN,https://digitalcollections.lib.washington.edu/...,https://digitalcollections.lib.washington.edu/...,erika-b.github.io/TJLS/items/largegroup1934.html,Japanese students--Washington (State)--Tacoma;...
24,Large group of students and faculty outside th...,Chapin Bowen Inc.,1931-08-30,Written in Japanese (translation): 20th annive...,"Tacoma, Washington, United States",NaN,NaN,NaN,Photographs of the Tacoma Japanese Language Sc...,image,image/jpeg,eng,NaN,NaN,https://digitalcollections.lib.washington.edu/...,https://digitalcollections.lib.washington.edu/...,erika-b.github.io/TJLS/items/largegroup1931.html,NaN
25,Large group of students and faculty kneeling a...,NaN,1937-05-23,Handwritten on verso: HATA,"Tacoma, Washington, United States",NaN,NaN,NaN,Photographs of the Tacoma Japanese Language Sc...,image,image/jpeg,eng,NaN,NaN,https://digitalcollections.lib.washington.edu/...,https://digitalcollections.lib.washington.edu/...,erika-b.github.io/TJLS/items/largegroup1937.html,Japanese students--Washington (State)--Tacoma;...
26,"Large group of students, faculty, and visiting...","Boland, M. D. (Marvin Dement)",Approximately 1933,Written on photo: Photograph commemorating the...,"Tacoma, Washington, United States",NaN,NaN,NaN,Photographs of the Tacoma Japanese Language Sc...,image,image/jpeg,eng,NaN,NaN,https://digitalcollections.lib.washington.edu/...,https://digitalcollections.lib.washington.edu/...,erika-b.github.io/TJLS/items/largegroup1933.html,Japanese students--Washington (State)--Tacoma;...
27,Japanese Language School above Buddhist Temple...,"Cysewski, Stephen",1979,Looking northeast,"Tacoma, Washington, United States",NaN,NaN,NaN,"Tacoma Public Library, Northwest Room",image,image/jpeg,eng,All rights reserved.,Contact the Northwest Room at Tacoma Public Li...,https://digitalcollections.lib.washington.edu/...,https://digitalcollections.lib.washington.edu/...,erika-b.github.io/TJLS/items/building1979.html,NaN
28,Tacoma's Japanese Language School: An Oral His...,"Hoffman, Lisa; Hanneman, Mary",2012,Graduates of the Japanese Language School in T...,"Tacoma, Washington, United States",NaN,NaN,NaN,UW Tacoma,image;MovingImage,video/mp4,eng,All rights reserved.,Contact UW Tacoma.,NaN,https://youtu.be/V_p8Zmz_nBk,erika-b.github.io/TJLS/items/booktrailer.html,NaN

In [7]:
#Run this a few times to see random entries in your dataframe
cb_normalized.sample(10)

,title,creator,date,description,location,people,organizations,places,source,type,format,language,rights,rightsstatement,object_thumb,object_location,reference_url,subject
2,Fumi (Sato) Hattori Oral History,"Hattori, Fumi (Sato)",2005-01-27,Fumi (Sato) Hattori looks back on her childhoo...,"Tacoma, Washington, United States; Ehime Prefe...","Sato, Hidamaru; Sato, Masahiro; Sato, Toshiats...",St. Paul Tacoma Lumber Company; Stadium High S...,St. Paul Avenue; Superior Hotel,Tacoma Japanese Language School Project,record,compound_object,eng,This item is protected by copyright and/or rel...,http://rightsstatements.org/vocab/InC-EDU/1.0/,erika-b.github.io/TJLS/objects/thumbs/shattori...,https://youtu.be/LdopnmPw9t4,erika-b.github.io/TJLS/items/shattori.html,NaN
16,Hanna Kae (Nakagawa) Torimaru Oral History,"Torimaru, Hanna Kae (Nakagawa)",2005-03-12,Hanna Kae Nakagawa Torimaru recounts her famil...,"Chicago, Illinois, United States; Tulelake, Ca...","Pei, I. M.; Torimaru, Hanna Kae (Nakagawa)",Tacoma Secretarial School; Central School; Lon...,Tacoma City Hall; State Cafe (Furusato); Carlt...,Tacoma Japanese Language School Project,record,compound_object,eng,This item is protected by copyright and/or rel...,http://rightsstatements.org/vocab/InC-EDU/1.0/,erika-b.github.io/TJLS/objects/thumbs/htorimar...,https://youtu.be/QBPnCDrNMW8,erika-b.github.io/TJLS/items/htorimaru.html,NaN
27,Japanese Language School above Buddhist Temple...,"Cysewski, Stephen",1979,Looking northeast,"Tacoma, Washington, United States",NaN,NaN,NaN,"Tacoma Public Library, Northwest Room",image,image/jpeg,eng,All rights reserved.,Contact the Northwest Room at Tacoma Public Li...,https://digitalcollections.lib.washington.edu/...,https://digitalcollections.lib.washington.edu/...,erika-b.github.io/TJLS/items/building1979.html,NaN
13,Mitsuo Takasugi image,NaN,2005-01-09,NaN,NaN,NaN,NaN,NaN,NaN,image;stillimage,image/jpeg,eng,NaN,NaN,erika-b.github.io/TJLS/objects/thumbs/mtakasug...,erika-b.github.io/TJLS/objects/mtakasugi_image...,erika-b.github.io/TJLS/items/mtakasugi3.html,NaN
25,Large group of students and faculty kneeling a...,NaN,1937-05-23,Handwritten on verso: HATA,"Tacoma, Washington, United States",NaN,NaN,NaN,Photographs of the Tacoma Japanese Language Sc...,image,image/jpeg,eng,NaN,NaN,https://digitalcollections.lib.washington.edu/...,https://digitalcollections.lib.washington.edu/...,erika-b.github.io/TJLS/items/largegroup1937.html,Japanese students--Washington (State)--Tacoma;...
24,Large group of students and faculty outside th...,Chapin Bowen Inc.,1931-08-30,Written in Japanese (translation): 20th annive...,"Tacoma, Washington, United States",NaN,NaN,NaN,Photographs of the Tacoma Japanese Language Sc...,image,image/jpeg,eng,NaN,NaN,https://digitalcollections.lib.washington.edu/...,https://digitalcollections.lib.washington.edu/...,erika-b.github.io/TJLS/items/largegroup1931.html,NaN
20,Betty Hiroko (Fukuhara) Yoshioka Oral History,"Yoshioka, Betty Hiroko (Fukuhara)",2005-03-10,"Hiroko ""Betty"" Fukuhara Yoshioka describes her...","Tacoma, Washington, United States; Chicago, Il...","Yoshioka, Akiko (Iris); Yoshioka, Sada (Sally)...",Central School; Morton M. McCarver Middle Scho...,Fawcett Avenue; Pearl Harbor,Tacoma Japanese Language School Project,record,compound_object,eng,This item is protected by copyright and/or rel...,http://rightsstatements.org/vocab/InC-EDU/1.0/,erika-b.github.io/TJLS/objects/thumbs/hyoshiok...,https://youtu.be/25-tdb1QQNw,erika-b.github.io/TJLS/items/hyoshioka.html,NaN
15,Taeko (Hoshiwara) Taniguichi image,NaN,2006-03-17,NaN,NaN,NaN,NaN,NaN,NaN,image;stillimage,image/jpeg,eng,NaN,NaN,erika-b.github.io/TJLS/objects/thumbs/ttanigui...,erika-b.github.io/TJLS/objects/ttaniguichi_ima...,erika-b.github.io/TJLS/items/ttaniguichi3.html,NaN
3,Fumi (Sato) Hattori image,NaN,2005-01-27,NaN,NaN,NaN,NaN,NaN,NaN,image;stillimage,image/jpeg,eng,NaN,NaN,erika-b.github.io/TJLS/objects/thumbs/shattori...,erika-b.github.io/TJLS/objects/shattori_image.jpg,erika-b.github.io/TJLS/items/shattori3.html,NaN
10,Chizu Takaoka Oral History,"Takaoka, Chizu",2005-03-12,Chizu Takaoka traces her family history from J...,"Tacoma, Washington, United States; Fukushima, ...","Tomita, Tainojo; Nihei, Kin; Suzuki, Daise; Ho...",Central School; Morton M. McCarver Middle Scho...,Wright Park; Pearl Harbor; Tule Lake War Reloc...,Tacoma Japanese Language School Project,record,compound_object,eng,This item is protected by copyright and/or rel...,http://rightsstatements.org/page/InC-EDU/1.0/?...,erika-b.github.io/TJLS/objects/thumbs/ctakaoka...,https://youtu.be/s6N63V7uSK4,erika-b.github.io/TJLS/items/ctakaoka.html,NaN

**H6** This is for bonus!
Try to write a pandas statement that will display your answer from **H4**. There are plenty of ways to do this, so feel free to use your imagination. What I have started for you here might not work, so feel free to change it as needed.

In [8]:
cb_normalized['format'].count()
print("The facet that shows up the most is Format. It is used {cb_normalized['format'].count()} times on the site.")

#I wanted to display the counts for all 3 facets in a table, so it's clear Format is most frequent.
#But why did "cb_normalized.groupby['facet'].count()" not work?

The facet that shows up the most is Format. It is used {cb_normalized['format'].count()} times on the site.


## All Done!

Congrats you are finished with this week's work. First save as PDF so that you can upload to the Course site then click the `Share` button above and enter `libraryjuicepresspython@gmail.com` so I can get a shared copy of your work.